### Articles

In [1]:
article = []

In [2]:
article.append({'text':'I saw the saw.', 'category':'story'})
article.append({'text':'I saw her standing there.', 'category':'story'})
article.append({'text':'Ofcourse I give her an umbrella.', 'category':'story'})
article.append({'text':'But she give me the saw.', 'category':'story'})
article.append({'text':'I come but she run.', 'category':'story'})

article.append({'text':'The moon is Earth’s closest neighbor.', 'category':'science'})
article.append({'text':'It is the brightest object in the night sky..', 'category':'science'})
article.append({'text':'Learn more about the moon.', 'category':'science'})
article.append({'text':'Scientists have studied the moon for thousands of years.', 'category':'science'})
article.append({'text':'The moon is about 4½ billion years old.', 'category':'science'})

article.append({'text':'People build homes.','category':'animal'})
article.append({'text':'A home keeps us warm and dry.', 'category': 'animal'})
article.append({'text':'It gives us a place to live.','category':'animal'})
article.append({'text':'Animals also build homes.','category':'animal'})
article.append({'text':'Read on to see how.','category':'animal'})

article.append({'text':'This is a human skeleton.','category':'health'})
article.append({'text':'It is made of bones.','category':'health'})
article.append({'text':'Bones shape and support your body.','category':'health'})
article.append({'text':'They also protect your organs.','category':'health'})
article.append({'text':'Calcium helps bones grow strong.','category':'health'})


In [3]:
article

[{'text': 'I saw the saw.', 'category': 'story'},
 {'text': 'I saw her standing there.', 'category': 'story'},
 {'text': 'Ofcourse I give her an umbrella.', 'category': 'story'},
 {'text': 'But she give me the saw.', 'category': 'story'},
 {'text': 'I come but she run.', 'category': 'story'},
 {'text': 'The moon is Earth’s closest neighbor.', 'category': 'science'},
 {'text': 'It is the brightest object in the night sky..',
  'category': 'science'},
 {'text': 'Learn more about the moon.', 'category': 'science'},
 {'text': 'Scientists have studied the moon for thousands of years.',
  'category': 'science'},
 {'text': 'The moon is about 4½ billion years old.', 'category': 'science'},
 {'text': 'People build homes.', 'category': 'animal'},
 {'text': 'A home keeps us warm and dry.', 'category': 'animal'},
 {'text': 'It gives us a place to live.', 'category': 'animal'},
 {'text': 'Animals also build homes.', 'category': 'animal'},
 {'text': 'Read on to see how.', 'category': 'animal'},
 {'t

### Import pandas

In [4]:
import pandas as pd

### Export to DataFrame

In [5]:
news_list = pd.DataFrame.from_dict(article)

In [6]:
news_list

category                                               text
0     story                                     I saw the saw.
1     story                          I saw her standing there.
2     story                   Ofcourse I give her an umbrella.
3     story                           But she give me the saw.
4     story                                I come but she run.
5   science              The moon is Earth’s closest neighbor.
6   science      It is the brightest object in the night sky..
7   science                         Learn more about the moon.
8   science  Scientists have studied the moon for thousands...
9   science            The moon is about 4½ billion years old.
10   animal                                People build homes.
11   animal                      A home keeps us warm and dry.
12   animal                       It gives us a place to live.
13   animal                          Animals also build homes.
14   animal                                Read on to see how.
15   health                          This is a human skeleton.
16   health                               It is made of bones.
17   health                 Bones shape and support your body.
18   health                     They also protect your organs.
19   health                   Calcium helps bones grow strong.

In [7]:
news_list.head(10)

category                                               text
0    story                                     I saw the saw.
1    story                          I saw her standing there.
2    story                   Ofcourse I give her an umbrella.
3    story                           But she give me the saw.
4    story                                I come but she run.
5  science              The moon is Earth’s closest neighbor.
6  science      It is the brightest object in the night sky..
7  science                         Learn more about the moon.
8  science  Scientists have studied the moon for thousands...
9  science            The moon is about 4½ billion years old.

In [8]:
news_list.category.value_counts()

animal     5
science    5
story      5
health     5
Name: category, dtype: int64

### Convert label to a numerical variable

In [9]:
# convert label to a numerical variable
news_list['label_num'] = news_list.category.map({'story':0, 'science':1, 'animal':2, 'health':3})

In [10]:
news_list

category                                               text  label_num
0     story                                     I saw the saw.          0
1     story                          I saw her standing there.          0
2     story                   Ofcourse I give her an umbrella.          0
3     story                           But she give me the saw.          0
4     story                                I come but she run.          0
5   science              The moon is Earth’s closest neighbor.          1
6   science      It is the brightest object in the night sky..          1
7   science                         Learn more about the moon.          1
8   science  Scientists have studied the moon for thousands...          1
9   science            The moon is about 4½ billion years old.          1
10   animal                                People build homes.          2
11   animal                      A home keeps us warm and dry.          2
12   animal                       It gives us a place to live.          2
13   animal                          Animals also build homes.          2
14   animal                                Read on to see how.          2
15   health                          This is a human skeleton.          3
16   health                               It is made of bones.          3
17   health                 Bones shape and support your body.          3
18   health                     They also protect your organs.          3
19   health                   Calcium helps bones grow strong.          3

### Split into training and testing sets

In [12]:
# split X and y into training and testing sets
from sklearn.model_selection import train_test_split

In [13]:
X = news_list.text
y = news_list.label_num
print(X.shape)
print(y.shape)

(20,)
(20,)


In [17]:
train_test_split?

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(18,)
(2,)
(18,)
(2,)


### Feature Extraction

In [52]:
#vect

In [53]:
from sklearn.feature_extraction.text import CountVectorizer

# instantiate the vectorizer
vect = CountVectorizer()

In [54]:
X_train

18                       They also protect your organs.
16                                 It is made of bones.
11                        A home keeps us warm and dry.
6         It is the brightest object in the night sky..
0                                        I saw the saw.
9               The moon is about 4½ billion years old.
12                         It gives us a place to live.
19                     Calcium helps bones grow strong.
8     Scientists have studied the moon for thousands...
14                                  Read on to see how.
15                            This is a human skeleton.
7                            Learn more about the moon.
2                      Ofcourse I give her an umbrella.
4                                   I come but she run.
5                 The moon is Earth’s closest neighbor.
1                             I saw her standing there.
10                                  People build homes.
13                            Animals also build

In [55]:
X_test

17    Bones shape and support your body.
3               But she give me the saw.
Name: text, dtype: object

In [56]:
y_train

18    3
16    3
11    2
6     1
0     0
9     1
12    2
19    3
8     1
14    2
15    3
7     1
2     0
4     0
5     1
1     0
10    2
13    2
Name: label_num, dtype: int64

In [58]:
# learn training data vocabulary, then use it to create a document-term matrix
vect.fit(X_train)
X_train_dtm = vect.transform(X_train)

# or

# equivalently: combine fit and transform into a single step
# X_train_dtm = vect.fit_transform(X_train)

In [24]:
X_train_dtm

<18x69 sparse matrix of type '<class 'numpy.int64'>'
	with 94 stored elements in Compressed Sparse Row format>

In [25]:
X_train_dtm

<18x69 sparse matrix of type '<class 'numpy.int64'>'
	with 94 stored elements in Compressed Sparse Row format>

In [27]:
# transform testing data (using fitted vocabulary) into a document-term matrix
X_test_dtm = vect.transform(X_test)
# X_test_dtm

<2x69 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

### Classification using NaiveBayes

In [59]:
# import and instantiate a Multinomial Naive Bayes model
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [60]:
# train the model using X_train_dtm (timing it with an IPython "magic command")
%time nb.fit(X_train_dtm, y_train)

CPU times: user 2.04 ms, sys: 917 µs, total: 2.96 ms
Wall time: 2.14 ms


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [61]:
# make class predictions for X_test_dtm
y_pred_class = nb.predict(X_test_dtm)

In [62]:
y_pred_class

array([3, 0])

In [63]:
# calculate accuracy of class predictions
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred_class)

1.0

In [64]:
y_test

17    3
3     0
Name: label_num, dtype: int64

In [65]:
y_pred_class

array([3, 0])

In [66]:
# print the confusion matrix
metrics.confusion_matrix(y_test, y_pred_class)

array([[1, 0],
       [0, 1]])

### Clasification test

In [67]:
new_article = ['People build house']
new_article_vect = vect.transform(new_article)
nb.predict(new_article_vect)

# {'animal':0, 'health':1, 'story':2, 'science':3}

array([2])

In [68]:
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler(with_mean = False)  
scaler.fit(X_train_dtm)

X_training_vector = scaler.transform(X_train_dtm)  
X_test_vector = scaler.transform(X_test_dtm)

/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:590: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


### Classification using SVM

In [69]:
from sklearn import svm
from sklearn.metrics import accuracy_score
clf = svm.SVC(kernel='linear')
print("Training Classifier...")
%time clf.fit(X_training_vector, y_train)
print("Predicting...")
prediction = clf.predict(X_test_vector)
print("Prediction:",prediction)
accuracy = accuracy_score(y_test, prediction)
# metrics.accuracy_score(y_test, y_pred_class)
print('Accuracy:', accuracy)

Training Classifier...
CPU times: user 2.24 ms, sys: 765 µs, total: 3.01 ms
Wall time: 5.17 ms
Predicting...
Prediction: [3 0]
Accuracy: 1.0


In [70]:
metrics.accuracy_score(y_test, prediction)

1.0

In [71]:
# print(y_test)
print(prediction)

[3 0]


In [72]:
new_article = ['saw your saw i']
new_article_vect = vect.transform(new_article)
clf.predict(new_article_vect)

# {'news':0, 'finance':1, 'hot':2, 'sport':3, 'travel':4}

array([0])

In [73]:
vect.get_feature_names()

['4½',
 'about',
 'also',
 'an',
 'and',
 'animals',
 'billion',
 'bones',
 'brightest',
 'build',
 'but',
 'calcium',
 'closest',
 'come',
 'dry',
 'earth',
 'for',
 'give',
 'gives',
 'grow',
 'have',
 'helps',
 'her',
 'home',
 'homes',
 'how',
 'human',
 'in',
 'is',
 'it',
 'keeps',
 'learn',
 'live',
 'made',
 'moon',
 'more',
 'neighbor',
 'night',
 'object',
 'of',
 'ofcourse',
 'old',
 'on',
 'organs',
 'people',
 'place',
 'protect',
 'read',
 'run',
 'saw',
 'scientists',
 'see',
 'she',
 'skeleton',
 'sky',
 'standing',
 'strong',
 'studied',
 'the',
 'there',
 'they',
 'this',
 'thousands',
 'to',
 'umbrella',
 'us',
 'warm',
 'years',
 'your']