In [28]:
corpus = ['I saw the saw.',
     'I saw her standing there.',
     'Ofcourse I give her an umbrella.',
     'But she give me the saw.',
     'I come but she run.']

In [29]:
# index_value={i[1]:i[0] for i in vectorizer.vocabulary_.items()}

In [30]:
# fully_indexed = []
# for row in X:
#     fully_indexed.append({index_value[column]:value for (column,value) in zip(row.indices,row.data)})

In [31]:
# fully_indexed

In [32]:
# index_value

In [33]:
# vectorizer.get_feature_names()

In [34]:
# import and instantiate CountVectorizer (with the default parameters)
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()

In [35]:
# CountVectorizer?

In [36]:
# learn the 'vocabulary' of the training data (occurs in-place)
vect.fit(corpus)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [37]:
# examine the fitted vocabulary
vect.get_feature_names()

['an',
 'but',
 'come',
 'give',
 'her',
 'me',
 'ofcourse',
 'run',
 'saw',
 'she',
 'standing',
 'the',
 'there',
 'umbrella']

In [38]:
# transform training data into a 'document-term matrix'
simple_train_dtm = vect.transform(corpus)

In [39]:
# convert sparse matrix to a dense matrix
simple_train_dtm.toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0],
       [1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0]])

In [40]:
import pandas as pd
# examine the vocabulary and document-term matrix together
pd.DataFrame(simple_train_dtm.toarray(), columns=vect.get_feature_names())

an  but  come  give  her  me  ofcourse  run  saw  she  standing  the  \
0   0    0     0     0    0   0         0    0    2    0         0    1   
1   0    0     0     0    1   0         0    0    1    0         1    0   
2   1    0     0     1    1   0         1    0    0    0         0    0   
3   0    1     0     1    0   1         0    0    1    1         0    1   
4   0    1     1     0    0   0         0    1    0    1         0    0   

   there  umbrella  
0      0         0  
1      1         0  
2      0         1  
3      0         0  
4      0         0

In [41]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())

['an', 'but', 'come', 'give', 'her', 'me', 'ofcourse', 'run', 'saw', 'she', 'standing', 'the', 'there', 'umbrella']


In [42]:
# index_value={i[1]:i[0] for i in vectorizer.vocabulary_.items()}

# fully_indexed = []
# for row in X:
#     fully_indexed.append({index_value[column]:value for (column,value) in zip(row.indices,row.data)})

In [43]:
pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names())

an       but      come      give       her       me  ofcourse  \
0  0.00000  0.000000  0.000000  0.000000  0.000000  0.00000   0.00000   
1  0.00000  0.000000  0.000000  0.000000  0.458270  0.00000   0.00000   
2  0.48214  0.000000  0.000000  0.388988  0.388988  0.00000   0.48214   
3  0.00000  0.400791  0.000000  0.400791  0.000000  0.49677   0.00000   
4  0.00000  0.444002  0.550329  0.000000  0.000000  0.00000   0.00000   

        run       saw       she  standing       the     there  umbrella  
0  0.000000  0.856606  0.000000  0.000000  0.515971  0.000000   0.00000  
1  0.000000  0.380406  0.000000  0.568014  0.000000  0.568014   0.00000  
2  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   0.48214  
3  0.000000  0.332693  0.400791  0.000000  0.400791  0.000000   0.00000  
4  0.550329  0.000000  0.444002  0.000000  0.000000  0.000000   0.00000

In [44]:
# example text for model testing
simple_test = ["i give the saw"]

In [45]:
# transform testing data into a document-term matrix (using existing vocabulary)
simple_test_dtm = vect.transform(simple_test)
simple_test_dtm.toarray()

array([[0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0]])

In [46]:
# examine the vocabulary and document-term matrix together
pd.DataFrame(simple_test_dtm.toarray(), columns=vect.get_feature_names())

an  but  come  give  her  me  ofcourse  run  saw  she  standing  the  \
0   0    0     0     1    0   0         0    0    1    0         0    1   

   there  umbrella  
0      0         0

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
corpus = []

corpus.append({'text':'I saw the saw.','sentiment':'0'})
corpus.append({'text':'I saw her standing there.', 'sentiment':'1'})
corpus.append({'text':'Ofcourse I give her an umbrella.','sentiment':'1'})
corpus.append({'text':'But she give me the saw.', 'sentiment':'-1'})
corpus.append({'text':'I come but she run.', 'sentiment':'-1'})

corpus.append({'text':'The moon is Earth’s closest neighbor.', 'sentiment':'0'})
corpus.append({'text':'It is the brightest object in the night sky..', 'sentiment':'1'})
corpus.append({'text':'Learn more about the moon.', 'sentiment':'1'})
corpus.append({'text':'Scientists have studied the moon for thousands of years.', 'sentiment':'0'})
corpus.append({'text':'The moon is about 4½ billion years old.', 'sentiment':'0'})

corpus.append({'text':'People build homes.','sentiment':'0'})
corpus.append({'text':'A home keeps us warm and dry.', 'sentiment': '0'})
corpus.append({'text':'It gives us a place to live.','sentiment':'-1'})
corpus.append({'text':'Animals also build homes.','sentiment':'-1'})
corpus.append({'text':'Read on to see how.','sentiment':'1'})

corpus.append({'text':'This is a human skeleton.','sentiment':'0'})
corpus.append({'text':'It is made of bones.','sentiment':'1'})
corpus.append({'text':'Bones shape and support your body.','sentiment':'0'})
corpus.append({'text':'They also protect your organs.','sentiment':'1'})
corpus.append({'text':'Calcium helps bones grow strong.','sentiment':'1'})

In [49]:
news_corpus = pd.DataFrame.from_dict(corpus)

In [50]:
X = news_corpus.text
y = news_corpus.sentiment
print(X.shape)
print(y.shape)

(20,)
(20,)


In [51]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)


(18,)
(2,)
(18,)
(2,)


In [52]:
news_corpus

sentiment                                               text
0          0                                     I saw the saw.
1          1                          I saw her standing there.
2          1                   Ofcourse I give her an umbrella.
3         -1                           But she give me the saw.
4         -1                                I come but she run.
5          0              The moon is Earth’s closest neighbor.
6          1      It is the brightest object in the night sky..
7          1                         Learn more about the moon.
8          0  Scientists have studied the moon for thousands...
9          0            The moon is about 4½ billion years old.
10         0                                People build homes.
11         0                      A home keeps us warm and dry.
12        -1                       It gives us a place to live.
13        -1                          Animals also build homes.
14         1                                Read on to see how.
15         0                          This is a human skeleton.
16         1                               It is made of bones.
17         0                 Bones shape and support your body.
18         1                     They also protect your organs.
19         1                   Calcium helps bones grow strong.

In [53]:
vect.fit(X_train)
X_train_dtm = vect.transform(X_train)


In [54]:
X_test_dtm = vect.transform(X_test)

In [55]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [56]:
%time nb.fit(X_train_dtm, y_train)

CPU times: user 1.42 ms, sys: 261 µs, total: 1.68 ms
Wall time: 1.47 ms


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [57]:
y_pred_class = nb.predict(X_test_dtm)

In [65]:
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred_class)

0.5

In [59]:
metrics.confusion_matrix(y_test, y_pred_class)

array([[1, 1],
       [0, 0]])

In [63]:
X_test

5    The moon is Earth’s closest neighbor.
0                           I saw the saw.
Name: text, dtype: object

In [68]:
test1 = ['saw your saw i']
new_article_vect = vect.transform(test1)
nb.predict(new_article_vect)

array(['1'], dtype='<U2')